name: Build SpacemiT K3 Firmware

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  TOOLCHAIN_URL: https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2026.06.06/riscv64-glibc-ubuntu-24.04-gcc.tar.xz
  CROSS_COMPILE: riscv64-unknown-linux-gnu-

permissions:
  contents: write

jobs:
  build:
    name: Build All Firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1

      - uses: actions/checkout@v6
        with:
          repository: 'openRuyi-Project/linux'
          path: 'linux'
          fetch-depth: 1

      - name: Install Dependencies
        run: make install-deps

      - name: Cache Linux Toolchain
        id: cache-linux-tc
        uses: actions/cache@v5
        with:
          path: /opt/riscv
          key: linux-toolchain-${{ env.TOOLCHAIN_URL }}

      - name: Setup Linux Toolchain
        if: steps.cache-linux-tc.outputs.cache-hit != 'true'
        run: curl -L --retry 3 --retry-delay 5 ${{ env.TOOLCHAIN_URL }} | tar -xJ -C /opt

      - name: Add Linux Toolchain to PATH
        run: echo "/opt/riscv/bin" >> $GITHUB_PATH

      - name: Cache Bare-metal Toolchain
        id: cache-bare-tc
        uses: actions/cache@v5
        with:
          path: toolchain
          key: bare-toolchain-spacemit-elf-newlib-v1.2.4

      - name: Download Bare-metal Toolchain
        if: steps.cache-bare-tc.outputs.cache-hit != 'true'
        run: make toolchain

      - name: Build
        run: make CROSS_COMPILE=${{ env.CROSS_COMPILE }} all

      - name: Symbolize ESOS boot exceptions
        run: |
          ADDR2LINE=toolchain/spacemit-toolchain-elf-newlib-x86_64-v1.2.4/bin/riscv64-unknown-elf-addr2line
          OBJDUMP=toolchain/spacemit-toolchain-elf-newlib-x86_64-v1.2.4/bin/riscv64-unknown-elf-objdump
          "$ADDR2LINE" -a -f -C -i -e output/esos/rt24_os0_rcpu.elf 0x1002132a4
          "$ADDR2LINE" -a -f -C -i -e output/esos/rt24_os1_rcpu.elf 0x100816af8
          "$OBJDUMP" -dSl --start-address=0x100213280 --stop-address=0x1002132c0 output/esos/rt24_os0_rcpu.elf
          "$OBJDUMP" -dSl --start-address=0x100816ad0 --stop-address=0x100816b20 output/esos/rt24_os1_rcpu.elf

      - name: Upload Firmware
        uses: actions/upload-artifact@v7
        with:
          name: bl-spacemit-k3
          path: dist/

      - name: Archive Firmware
        if: github.ref_type == 'tag'
        run: tar -cJf bl-spacemit-k3-${{ github.ref_name }}.tar.xz -C dist .

      - name: Upload Firmware to Release (on Tag Push)
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v3
        with:
          name: Boot Firmware for SpacemiT K3 ${{ github.ref_name }}
          files: bl-spacemit-k3-${{ github.ref_name }}.tar.xz
          prerelease: true
